### ISSUE TITLE
Better user flow when another app is detected running in port 3000

### ISSUE THREAD

**Issue by sent-hil** [bvallelunga/Phonegap.kdapp#3]
- Exit button if user doesn't want to continue
- If another instance of phonegap app is running, 
  - ask to continue without killing it
  - if on not port 3000 just continue on.

**Comment by bvallelunga** [comment]
@sent-hil LOL, 2 years late it gets closed.

**Comment by sent-hil** [comment]
Well I was hoping you would fix it eventually :) ... was cleaning up my issues tonight.

**Comment by bvallelunga** [comment]
Haha. Hows Koding doing?
